name: Terraform deploy
on:
  repository_dispatch:
    types: [image-pushed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          auto_approve: true
